### ISSUE TITLE
Refactoring callback to async-await code

### ISSUE THREAD

**Issue by Ts-A** [ujjwal-kr/positive-vibes#34]
Currently bcrypt and jwt are using callback functions in [auth.js](https://github.com/ujjwal-kr/positive-vibes/blob/master/server/routes/auth/auth.js) which might lead to callback hell if further additions are to be made. There are synchronous lib functions available in these packages. Can you assign me the task of refactoring to async-await style?

**Comment by ujjwal-kr** [comment]
sorry for the late response, you can surely send a PR to improve the code!
